@startuml
skinparam dpi 200
skinparam defaultFontName Roboto
skinparam defaultFontSize 16
skinparam shadowing false
skinparam backgroundColor #f8f9fa
skinparam handwritten false

salt
{
{T
+ <size:20><b>🚀 Deployment Repository</b></size>
++
++ <color:#007BFF><b>📂 common</b></color>                               | <color:#007BFF>🔹 Common variables and modules.</color>
+++ <color:#007BFF><b>📂 environments</b></color>                        | <color:#007BFF>🌎 Global variables.</color>
++++ <color:#00A896>📜 env_<environment>_common.tfvars</color>           | <color:#00A896>📌 Global Env. specific TF vars.</color>
++++ <color:#FF6B6B>🔖 env_<environment>.hcl</color>                     | <color:#FF6B6B>⚙️ Global Env. specific wrapper vars.</color>
++++ <color:#00A896>📜 env_<environment>_<site>_common.tfvars</color>    | <color:#00A896>📌 Global Env. and site specific TF vars.</color>
++++ <color:#FF6B6B>🔖 env_<environment>_<site>.hcl</color>              | <color:#FF6B6B>⚙️ Global Env. and site specific wrapper vars.</color>
++
++ <color:#007BFF><b>📂 <resource></b></color>                           | <color:#007BFF>📦 Resource to be deployed.</color>
+++ <color:#007BFF><b>📂 environments</b></color>                        | <color:#007BFF>🔄 Resource-specific variables.</color>
++++ <color:#00A896>📜 env_<environment>.tfvars</color>                  | <color:#00A896>📌 Resource Env. specific TF vars.</color>
++++ <color:#00A896>📜 env_<environment>_<site>.tfvars</color>           | <color:#00A896>📌 Resource Env. and site specific TF vars.</color>
+++ <color:#6A4C93>🔷 main.tf</color>                                    | <color:#6A4C93>📜 Resource Terraform script.</color>
+++ <color:#6A4C93>🔷 variables.tf</color>                               | <color:#6A4C93>⚙️ Resource TF variables.</color>
+++ <color:#6A4C93>🔷 output.tf</color>                                  | <color:#6A4C93>📤 Resource TF outputs.</color>
++
++ <color:#007BFF><b>📂 <resource_groups></b></color>                    | <color:#007BFF>📦 Group of resources to be deployed.</color>
+++ <color:#007BFF><b>📂 <sub_resource></b></color>                      | <color:#007BFF>📦 Sub-Resource deployment.</color>
++++ <color:#007BFF><b>📂 environments</b></color>                       | <color:#007BFF>🔄 Sub-Resource variables.</color>
+++++ <color:#00A896>📜 env_<environment>.tfvars</color>                 | <color:#00A896>📌 Sub-Resource Env. specific TF vars.</color>
+++++ <color:#00A896>📜 env_<environment>_<site>.tfvars</color>          | <color:#00A896>📌 Sub-Resource Env. and site specific TF vars.</color>
++++ <color:#6A4C93>🔷 main.tf</color>                                   | <color:#6A4C93>📜 Sub-Resource Terraform script.</color>
++++ <color:#6A4C93>🔷 variables.tf</color>                              | <color:#6A4C93>⚙️ Sub-Resource TF variables.</color>
++++ <color:#6A4C93>🔷 output.tf</color>                                 | <color:#6A4C93>📤 Sub-Resource TF outputs.</color>
++
++ <color:#007BFF>📄 .gitignore</color>                                  | <color:#007BFF>📌 Repository maintenance.</color>
}
}
@enduml